language: php

php:
    - 5.3
    - 5.4

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
    - export HOST="behat.local"
    - export DATABASE="behat"
    - export BROWSER="phantomjs"
    - export WEB_DIRECTORY="./web"
    - sh -e .travis/scripts/apt-get.sh
    - sh -e .travis/scripts/apache2-vhost.sh $HOST $(readlink -f $WEB_DIRECTORY)
    - sh -e .travis/scripts/apache2-configure.sh $HOST
    - sh -e .travis/scripts/mysql.sh "test_$DATABASE"
    - sh -e .travis/scripts/sahi-install.sh

before_script:
    - sh -e .travis/scripts/sf2-configure.sh $DATABASE
    - sh -e .travis/scripts/behat-configure.sh $HOST $BROWSER "" "" $(readlink -f behat.yml-dist)
    - sh -e .travis/scripts/sahi-configure.sh
    - sh -e .travis/scripts/sf2-init.sh
    - sh -e .travis/scripts/sahi-start.sh

script: 
    - php behat.phar --profile=travis @BehatViewerBundle
