<?php

namespace jubianchi\BehatViewerBundle\Entity\Repository;

use \Doctrine\ORM\EntityRepository,
    \Doctrine\ORM\Query\Expr,
    \jubianchi\BehatViewerBundle\Entity;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends EntityRepository
{
    public function findBySlugAndBuild($slug, Entity\Build $build)
    {
        return $this->createQueryBuilder('f')
            ->select(array('f', 'fb'))
            ->join('f.builds', 'fb', Expr\Join::WITH, 'fb = :build')
            ->where('f.slug = :slug')
            ->setParameter('slug', $slug)
            ->setParameter('build', $build)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findByTagAndBuild(Entity\Tag $tag, Entity\Build $build)
    {
        return $this->createQueryBuilder('f')
            ->select(array('f', 'ft', 'fb'))
            ->join('f.tags', 'ft', Expr\Join::WITH, 'ft = :tag')
            ->join('f.builds', 'fb', Expr\Join::WITH, 'fb = :build')
            ->setParameter('tag', $tag)
            ->setParameter('build', $build)
            ->getQuery()
            ->getResult();
    }
}