<?php

namespace jubianchi\BehatViewerBundle\Entity\Repository;

use \Doctrine\ORM\EntityRepository,
    \Doctrine\ORM\Query\Expr,
    \jubianchi\BehatViewerBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
}