<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class jubianchiBehatViewerBundleEntityBuildProxy extends \jubianchi\BehatViewerBundle\Entity\Build implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setProject(\jubianchi\BehatViewerBundle\Entity\Project $project)
    {
        $this->__load();
        return parent::setProject($project);
    }

    public function getProject()
    {
        $this->__load();
        return parent::getProject();
    }

    public function addFeature(\jubianchi\BehatViewerBundle\Entity\Feature $features)
    {
        $this->__load();
        return parent::addFeature($features);
    }

    public function getFeatures()
    {
        $this->__load();
        return parent::getFeatures();
    }

    public function getScenarios()
    {
        $this->__load();
        return parent::getScenarios();
    }

    public function getStepsHavingStatus($status = NULL)
    {
        $this->__load();
        return parent::getStepsHavingStatus($status);
    }

    public function getStepsHavingStatusCount($status = NULL)
    {
        $this->__load();
        return parent::getStepsHavingStatusCount($status);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date', 'project', 'features');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}